# Generated by Django 4.1.6 on 2023-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=500)),
            ],
        ),
    ]
